<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.01" os="Windows 7" host="VQTOOLS116"><DocLocation><![CDATA[E:\CI_WS\workspace\JPetStoreMavenDemo\JPetStore_HPUFT\demo10]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[demo10]]></DName>
<Res><![CDATA[demo10]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="18" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[JPetStore Demo]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2/20/2017 - 18:56:09]]></Time>
<TimeTick>1487597169</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[JPetStore Demo]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2/20/2017 - 18:56:09]]></Time>
<TimeTick>1487597169</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Enter the Store.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/20/2017 - 18:56:09]]></Time>
<TimeTick>1487597169</TimeTick>
<NodeArgs eType="Replay" icon="23" nRep="12" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Enter the Store.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="22" nRep="11" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[JPetStore Demo]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[JPetStore Demo_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2/20/2017 - 18:56:14]]></Time>
<TimeTick>1487597174</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[cats_icon.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/20/2017 - 18:56:14]]></Time>
<TimeTick>1487597174</TimeTick>
<NodeArgs eType="Replay" icon="24" nRep="16" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[cats_icon.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="22" nRep="15" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[JPetStore Demo_2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[JPetStore Demo_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2/20/2017 - 18:56:19]]></Time>
<TimeTick>1487597179</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[FL-DSH-01.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/20/2017 - 18:56:19]]></Time>
<TimeTick>1487597179</TimeTick>
<NodeArgs eType="Replay" icon="23" nRep="20" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[FL-DSH-01.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="22" nRep="19" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[JPetStore Demo_3]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[JPetStore Demo_4]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2/20/2017 - 18:56:24]]></Time>
<TimeTick>1487597184</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[button_add_to_cart.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/20/2017 - 18:56:24]]></Time>
<TimeTick>1487597184</TimeTick>
<NodeArgs eType="Replay" icon="24" nRep="24" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[button_add_to_cart.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="22" nRep="23" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[JPetStore Demo_4]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[JPetStore Demo_5]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2/20/2017 - 18:56:29]]></Time>
<TimeTick>1487597189</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[button_checkout.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/20/2017 - 18:56:29]]></Time>
<TimeTick>1487597189</TimeTick>
<NodeArgs eType="Replay" icon="24" nRep="28" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[button_checkout.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="22" nRep="27" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[JPetStore Demo_5]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[JPetStore Demo_6]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2/20/2017 - 18:56:34]]></Time>
<TimeTick>1487597194</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[button_continue.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/20/2017 - 18:56:34]]></Time>
<TimeTick>1487597194</TimeTick>
<NodeArgs eType="Replay" icon="24" nRep="32" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[button_continue.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="22" nRep="31" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[JPetStore Demo_6]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[JPetStore Demo_7]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2/20/2017 - 18:56:39]]></Time>
<TimeTick>1487597199</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[JPetStore Demo_7.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/20/2017 - 18:56:39]]></Time>
<TimeTick>1487597199</TimeTick>
<NodeArgs eType="Replay" icon="22" nRep="36" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[JPetStore Demo_7.Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="22" nRep="35" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[JPetStore Demo_7]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[JPetStore Demo.Close All Tabs]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/20/2017 - 18:56:44]]></Time>
<TimeTick>1487597204</TimeTick>
<NodeArgs eType="Replay" icon="21" nRep="37" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[JPetStore Demo.Close All Tabs]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="21" nRep="10" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[JPetStore Demo]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2/20/2017 - 18:56:08" eTime="2/20/2017 - 18:56:45" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="20" nRep="7" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="19" nRep="6" >
<Disp><![CDATA[demo10 Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="2/20/2017 - 18:56:04" eTime="2/20/2017 - 18:56:45" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="17" nRep="3" >
<Disp><![CDATA[Test demo10 Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>